title:              Economics and Data Science
email:              danial.syed1@outlook.com
description:        Here I dive into my research and experiences leveraging frontier data science methods for energy & environment challenges.
author:             M.Danial Syed
baseurl:            ""
url:                "https://mdanialsyed.github.io"

# Social Profiles
twitter_username:   
github_username:   https://github.com/MDanialSyed
facebook_username:  
instagram_username:  
linkedin_username: https://www.linkedin.com/in/danialsyedm/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge
